### ISSUE TITLE
some error in gulp build with 8.25.0

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#10770]
## Type of issue
build error

## Description
seem to be getting some error in build when using:  gulp build --disable NATIVE --modules=modulesVideo.json

## Steps to reproduce
use command: gulp build --disable NATIVE --modules=modulesVideo.json

module file is there, as has been with previous builds.

## Test page
not applicable

### Expected results

clean build

### Actual results

throws this:

![prebid_js_—_Prebid_js](https://github.com/prebid/Prebid.js/assets/8503167/c9923870-fa19-40b6-a3b9-c5fc703ebc91)

![prebid_js_—_Prebid_js](https://github.com/prebid/Prebid.js/assets/8503167/71b147ac-f7af-4ead-a879-d95fd6969ba1)

some folder /creative  now seems to be there, sure it wasnt there before:
![prebid_js_—_Prebid_js](https://github.com/prebid/Prebid.js/assets/8503167/9db36a3a-4933-45b1-a0a4-c1a15e690328)

## Platform details
mac

**Comment by dgirardi** [comment]
Can you try `npm ci` before `gulp build`? 8.25 added a new dependency, and that log complains that it can't find it (`Cannot find module 'node-html-parser'`).

**Comment by spormeon** [comment]
ok, ye, thats got it, cheers
