### ISSUE TITLE
circular dependency between util.js and config.js

### ISSUE THREAD

**Issue by cazyw** [prebid/Prebid.js#6023]
## Type of issue
Possible bug - although since nobody else has complained about this, there must be a workaround

## Description
We have been running Prebid without problems up to version 3.15.0. When we upgraded to 3.16.0 (and any version after), running it on a site results in the following error:

`TypeError: p.getParameterByName is not a function`

I've narrowed it down to the change here introduced in 3.16.0 https://github.com/prebid/Prebid.js/pull/5092

and in particular changing this in config.js

`const DEFAULT_DEBUG = (parseQS(window.location.search)[CONSTANTS.DEBUG_MODE] || '').toUpperCase() === 'TRUE';`

to this

`const DEFAULT_DEBUG = utils.getParameterByName(CONSTANTS.DEBUG_MODE).toUpperCase() === 'TRUE';`

config.js imports utils.js `const utils = require('./utils.js');` but utils.js also imports config.js `import { config } from './config.js';`

If I comment out the import inside utils.js, everything loads fine. If I add the line back in, the error appears. 
This circular dependency is causing issues because the DEFAULT_DEBUG is now calling the `utils.getParameterByName` immediately, but `utils` hasn't finished loading yet so `getParameterByName` is not available.

I have not seen anyone else mention this specific error so is there some setting in webpack or babel etc that allows this to work 
for others?

We're using prebid with `import prebid from 'prebid.js';`, as soon as this import is included, the error appears.

## Steps to reproduce
Upgrade from Prebid 3.15.0 to 3.16.0
We did not change anything else in our implementation

## Test page
N/A

### Expected results
Prebid loads as usual on sites

### Actual results
This error appears breaking all the ads `TypeError: p.getParameterByName is not a function`

## Platform details
Prebid.js version 3.16.0 and up (have tried with latest 4.17.0)
Chrome 86
Node 10 (have tried v12 as well)
Webpack 4.35
Babel 7

## Other information
This is the PR change which seems to have introduced the issue  https://github.com/prebid/Prebid.js/pull/5092

**Comment by cazyw** [comment]
As a follow-up, we got this working by setting `optimization.concatenateModules: false`.

Looks like the mix of module formats in prebid.js was causing issues for us.

**Comment by markplewis** [comment]
I'm also experiencing this issue. We have a React app, so we're using a Webpack dynamic import to pull in the Prebid NPM package and all of the adapter modules that we need.

We started with `prebid.js` version `4.20.0`, then tried downgrading to `3.22.0`, but the `getParameterByName is not a function` error didn't disappear until we downgraded to `3.15.0`.

Is there a fix planned for version `5`, perhaps?

**Comment by ChrisHuie** [comment]
@markplewis are you still working around this issue? I can do a bit more research on this and see what solutions may be possible.

**Comment by markplewis** [comment]
Sorry @ChrisHuie, I didn't notice your reply until now. We downgraded to version `3.15.0` and haven't changed it since. This is working for us now, but it would be nice to be able to upgrade to a newer version eventually. I'll try testing the latest version when a new one is released. Thanks!
