### ISSUE TITLE
TypeError: pbjs.processQueue is not a function

### ISSUE THREAD

**Issue by Elardzhi** [prebid/Prebid.js#3465]
## Type of issue
Error message

## Description
After updating to 1.38 I get this error in my console: "TypeError: pbjs.processQueue is not a function". 

## Steps to reproduce
gulp serve on local PC with "Hello world" example

**Comment by snapwich** [comment]
I think you might need to `npm install`

let me know if that fixes your problem.

**Comment by bretg** [comment]
@Elardzhi - if `npm install` doesn't fix, feel free to re-open with more details.
